global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      resion: tokyo
      env: test 
      monitor: 'codelab-monitor'

alerting:
 alertmanagers:
 - static_configs:
   - targets:
      - alertmanager:9093

rule_files:
 - rules.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
         - localhost:9090
  - job_name: 'node-exporter'
    static_configs:
      - targets:
         - 192.168.11.2:9100
  - job_name: 'python-1'
    static_configs:
      - targets:
         - python3:8000
  - job_name: 'nodejs-sample'
    static_configs:
      - targets:
         - nodejssample:3000
        labels:
         group: nodejs-group
  - job_name: 'blackbox-test'
    static_configs:
      - targets:
         - blackbox-exporter:9115
        labels:
         group: blackbox-exporter
  - job_name: 'consul_test'
    static_configs:
      - targets:
         - consul:8300

